const championshipCars = [
    {
        name: "Alfa Romeo 158",
        year: 1950,
        team: "Alfa Romeo",
        engineName:"Alfa Romeo 158/159",
        engineConfig:"Straight-8 Front Mounted",
        compressor:"Roots type supercharger",
        engineDisplacement:"1479cc",
        enginePower:"350BHP @8500rpm",
        transmission:"Alfa 5-speed manual",
        tyres:["Pirelli"],
        chasis:"Single Seater Tubular Frame",
        weight:"700kg",
        drivers: ["Giuseppe Farina", "Juan Manuel Fangio", "Luigi Fagiolli"],
        constructorPoints: 81,
        image: "/assets/1950-1959/1950AlfaRomeo158.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Alfa Romeo 159",
        year: 1951,
        team: "Alfa Romeo",
        engineName:"Alfa Romeo 158/159",
        engineConfig:"Straight-8 Front Mounted",
        compressor:"2 Roots type supercharger",
        engineDisplacement:"1479cc",
        enginePower:"425BHP @9300rpm",
        transmission:"Alfa 4-speed manual",
        tyres:["Pirelli"],
        chasis:"Single Seater Tubular Frame",
        weight:"710kg",
        drivers: ["Juan Manuel Fangio", "Giuseppe Farina", "Felice Bonetto", "Luigi Fagiolli", "Consalvo Sanesi", "Toulo de Graffenried"],
        constructorPoints: 66,
        image: "/assets/1950-1959/1951AlfaRomeo159.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Ferrari 500",
        year: 1952,
        team: "Ferrari",
        engineName:"Ferrari Lampredi",
        engineConfig:"Inline 4 Front Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"1985cc",
        enginePower:"185BHP @7500rpm",
        transmission:"Ferrari 4-speed manual",
        tyres:["Pirelli", "Dunlop", "Englebert"],
        chasis:"Single Seater Tubular Frame",
        weight:"560kg",
        drivers: ["Alberto Ascari", "Giuseppe Farina", "Pierro Taruffi", "Rudi Fischer", "Luigi Villoresi"],
        constructorPoints: 100,
        image: "/assets/1950-1959/1952Ferrari500.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Ferrari 500",
        year: 1953,
        team: "Ferrari",
        engineName:"Ferrari Lampredi",
        engineConfig:"Inline 4 Front Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"1985cc",
        enginePower:"185BHP @7500rpm",
        transmission:"Ferrari 4-speed manual",
        tyres:["Pirelli", "Dunlop", "Englebert"],
        chasis:"Single Seater Tubular Frame",
        weight:"560kg",
        drivers: ["Alberto Ascari", "Giuseppe Farina", "Mike Hawthorn", "Luigi Villoresi"],
        constructorPoints: 96.5,
        image: "/assets/1950-1959/1953Ferrari500.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Mercedes-Benz W196",
        year: 1954,
        team: "Mercedes-Benz",
        engineName:"Mercedes-Benz 196",
        engineConfig:"Inline 8 Front Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2496cc",
        enginePower:"257BHP @8250rpm",
        transmission:"Mercedes 5-speed manual",
        tyres:["Continental"],
        chasis:"Single Seater Fackverksframe",
        weight:"700kg",
        drivers: ["Juan Manuel Fangio", "Karl Kling", "Hans Herrmann"],
        constructorPoints: 62,
        image: "/assets/1950-1959/1954MercedesW196.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Mercedes-Benz W196",
        year: 1955,
        team: "Mercedes-Benz",
        engineName:"Mercedes-Benz 196",
        engineConfig:"Inline 8 Front Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2496cc",
        enginePower:"257BHP @8250rpm",
        transmission:"Mercedes 5-speed manual",
        tyres:["Continental"],
        chasis:"Single Seater Fackverksframe",
        weight:"700kg",
        drivers: ["Juan Manuel Fangio", "Stirling Moss", "Pierro Taruffi" , "Karl Kling", "Hans Herrmann"],
        constructorPoints: 78,
        image: "/assets/1950-1959/1955MercedesW196Monza.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Lancia-Ferrari D50",
        year: 1956,
        team: "Ferrari",
        engineName:"Lancia-Ferrari DS50",
        engineConfig:"V8 Front Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2488cc",
        enginePower:"250BHP @8100rpm",
        transmission:"Ferrari 5-speed manual",
        tyres:["Pirelli", "Englebert"],
        chasis:"Single Seater Fackverksframe",
        weight:"650kg",
        drivers: ["Juan Manuel Fangio", "Peter Collins", "Eugenio Castellotti" , "Paul Frere", "Luigi Musso", "Alfonso de Portago", "Olivier Gendebien"],
        constructorPoints: 77.5,
        image: "/assets/1950-1959/1956FerrariD50.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Maserati 250F",
        year: 1957,
        team: "Maserati",
        engineName:"Maserati 250F",
        engineConfig:"V12 Front Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2491cc",
        enginePower:"310BHP @9300rpm",
        transmission:"Maserati 5-speed manual",
        tyres:["Pirelli"],
        chasis:"Single Seater Steel Tubular Space Frame",
        weight:"650kg",
        drivers: ["Juan Manuel Fangio", "Masten Gregory", "Jean Behra" , "Carlos Menditeguy", "Giorgio Scarlatti"],
        constructorPoints: 71,
        image: "/assets/1950-1959/1957Maserati250F.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Ferrari Dino 246 F1",
        year: 1958,
        team: "Ferrari",
        engineName:"Ferrari Dino 246",
        engineConfig:"V6 Front Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2417cc",
        enginePower:"280BHP @8500rpm",
        transmission:"Ferrari 4-speed manual",
        tyres:["Dunlop"],
        chasis:"Single Seater Fackverksframe",
        weight:"560kg",
        drivers: ["Mike Hawthorn", "Peter Collins", "Luigi Musso" , "Phil Hill", "Wolfgang von Trips"],
        constructorPoints: 40,
        image: "/assets/1950-1959/1958FerrariDino246.jpg",
        isWDC: true,
        isWCC: false,
    },
    {
        name: "Vanwall VW5",
        year: 1958,
        team: "Vanwall",
        engineName:"Vanwall VW5",
        engineConfig:"Straight 4 Front Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2490cc",
        enginePower:"285BHP @7300rpm",
        transmission:"Vanwall 5-speed manual",
        tyres:["Dunlop"],
        chasis:"Single Seater MultiTubular Space Frame",
        weight:"640kg",
        drivers: ["Stirling Moss", "Tony Brooks", "Stuart Lewis-Evans" , "Phil Hill", "Wolfgang von Trips"],
        constructorPoints: 48,
        image: "/assets/1950-1959/1958VanwallVW5.jpg",
        isWDC: false,
        isWCC: true,
    },
    {
        name: "Cooper Climax T51",
        year: 1959,
        team: "Cooper Climax",
        engineName:"Coventry Climax",
        engineConfig:"Inline 4 Rear Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2495cc",
        enginePower:"240BHP @6750rpm",
        transmission:"Citroen 5-speed manual",
        tyres:["Dunlop"],
        chasis:"Single Seater Steel Space Frame",
        weight:"701kg",
        drivers: ["Jack Brabham", "Stirling Moss", "Maurice Trintignant" , "Bruce McLaren", "Masten Gregory", "Harry Schell"],
        constructorPoints: 40,
        image: "/assets/1950-1959/1959CooperClimaxT51.jpg",
        isWDC: true,
        isWCC: true,
    },

    {
        name: "Cooper Climax T53",
        year: 1960,
        team: "Cooper Climax",
        engineName:"Coventry Climax FPF",
        engineConfig:"Straight 4 Rear Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2495cc",
        enginePower:"230BHP @7000rpm",
        transmission:"Cooper 5-speed manual",
        tyres:["Dunlop"],
        chasis:"Single Seater Steel Space Frame",
        weight:"500kg",
        drivers: ["Jack Brabham", "Bruce McLaren", "Phil Hill", "Olivier Gendebien", "Tony Brooks", "Henry Taylor", "Lucien Bianchi", "Ron Flockhart"],
        constructorPoints: 48,
        image: "/assets/1960-1969/1960CooperClimaxT53.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Ferrari 156",
        year: 1961,
        team: "Ferrari",
        engineName:"Ferrari Type 178",
        engineConfig:"V6 120degree Mid Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"1476cc",
        enginePower:"190BHP @9500rpm",
        transmission:"Ferrari Type 543/C-5 speed manual",
        tyres:["Dunlop"],
        chasis:"Single Seater Tubular Space Frame",
        weight:"420kg",
        drivers: ["Phill Hill", "Wolfgang von Trips", "Richie Ginther" , "Giancarlo Baghetti"],
        constructorPoints: 40,
        image: "/assets/1960-1969/1961Ferrari156F1.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "BRM P57",
        year: 1962,
        team: "BRM",
        engineName:"BRM P56",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"1498cc",
        enginePower:"188BHP @10250rpm",
        transmission:"BRM 6-speed Colloti manual",
        tyres:["Dunlop"],
        chasis:"Single Seater Tubular Space Frame",
        weight:"494kg",
        drivers: ["Graham Hill", "Richie Ginther"],
        constructorPoints: 42,
        image: "/assets/1960-1969/1962BRMP57.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Lotus Climax 25",
        year: 1963,
        team: "Lotus Climax",
        engineName:"Coventry Climax FWMV",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"1496cc",
        enginePower:"195BHP @8200rpm",
        transmission:"ZF 5DS10 5-speed manual",
        tyres:["Dunlop"],
        chasis:"Single Seater Alumunium Monococoque",
        weight:"451kg",
        drivers: ["Jim Clark", "Trevor Taylor", "Bernard Collomb" , "Mike Spence", "Pedro Rodriguez", "Ernie Pieterse"],
        constructorPoints: 54,
        image: "/assets/1960-1969/1963Lotus25.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Ferrari 158 F1",
        year: 1964,
        team: "Ferrari",
        engineName:"Ferrari Type 205/B",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"1489cc",
        enginePower:"210BHP @11000rpm",
        transmission:"Ferrari Type 543C/5-speed manual",
        tyres:["Dunlop"],
        chasis:"Single Seater Type 579 tubular semi-monocoque",
        weight:"468kg",
        drivers: ["John Surtees", "Lorenzo Bandini", "Pedro Rodriguez"],
        constructorPoints: 45,
        image: "/assets/1960-1969/1964Ferrari158F1.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Lotus Climax 33",
        year: 1965,
        team: "Lotus Climax",
        engineName:"Coventry Climax FWMV",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"1497cc",
        enginePower:"205BHP",
        transmission:"ZF 5-speed manual",
        tyres:["Dunlop"],
        chasis:"Single Seater Alumunium Monocoque",
        weight:"451kg",
        drivers: ["Jim Clark", "Mike Spence"],
        constructorPoints: 54,
        image: "/assets/1960-1969/1965Lotus33.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Brabham Repco BT19",
        year: 1966,
        team: "Brabham Repco",
        engineName:"Repco 620",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2955cc",
        enginePower:"296BHP",
        transmission:"Hewland HD/DG 5-speed manual",
        tyres:["Goodyear"],
        chasis:"Single Seater steel spaceframe",
        weight:"518kg",
        drivers: ["Jack Brabham", "Denny Hulme"],
        constructorPoints: 42,
        image: "/assets/1960-1969/1966BrabhamBT19.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Brabham Repco BT24",
        year: 1967,
        team: "Brabham Repco",
        engineName:"Repco 740",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2994cc",
        enginePower:"345BHP",
        transmission:"Hewland DG300 5-speed manual",
        tyres:["Goodyear"],
        chasis:"Single Seater steel spaceframe",
        weight:"490kg",
        drivers: ["Denny Hulme", "Jack Brabham", "Guy Ligier"],
        constructorPoints: 63,
        image: "/assets/1960-1969/1967BrabhamBT24.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Lotus Ford 49B",
        year: 1968,
        team: "Lotus Ford",
        engineName:"Ford Cosworth DFV",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2998cc",
        enginePower:"430BHP @9500rpm",
        transmission:"Hewland Lotus 5-speed manual",
        tyres:["Firestone", "Dunlop"],
        chasis:"Single Seater Alumunium Monocoque",
        weight:"501kg",
        drivers: ["Graham Hill", "Jo Siffert", "Jim Clark", "Jackie Oliver"],
        constructorPoints: 62,
        image: "/assets/1960-1969/1968Lotus49B.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Matra Ford MS80",
        year: 1969,
        team: "Matra Ford",
        engineName:"Ford Cosworth DFV",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2993cc",
        enginePower:"420BHP @9500rpm",
        transmission:"Hewland Lotus 5-speed manual",
        tyres:["Dunlop"],
        chasis:"Single Seater Alumunium Monocoque",
        weight:"540kg",
        drivers: ["Jackie Stewart", "Jean-Pierre Beltoise", "Johnny Servoz-Gavin"],
        constructorPoints: 66,
        image: "/assets/1960-1969/1969MatraMS80.jpg",
        isWDC: true,
        isWCC: true,
    },

    {
        name: "Lotus Ford 72",
        year: 1970,
        team: "Lotus Ford",
        engineName:"Ford Cosworth DFV",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2993cc",
        enginePower:"450BHP @10800rpm",
        transmission:"Hewland FG400 5-speed manual",
        tyres:["Firestone"],
        chasis:"Single Seater Alumunium Monocoque",
        weight:"550kg",
        drivers: ["Jochen Rindt", "Emerson Fittipaldi", "Graham Hill", "Reine Wisell", "John Miles"],
        constructorPoints: 59,
        image: "/assets/1970-1979/1970Lotus72.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Tyrrell Ford 003",
        year: 1971,
        team: "Tyrrell Ford",
        engineName:"Ford Cosworth DFV",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2993cc",
        enginePower:"450BHP @10800rpm",
        transmission:"Hewland FG400 5-speed manual",
        tyres:["Goodyear"],
        chasis:"Single Seater Alumunium Monocoque",
        weight:"560kg",
        drivers: ["Jackie Stewart", "Francois Cevert"],
        constructorPoints: 73,
        image: "/assets/1970-1979/1971Tyrrell003.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Lotus Ford 72D",
        year: 1972,
        team: "Lotus Ford",
        engineName:"Ford Cosworth DFV",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2993cc",
        enginePower:"450BHP @10800rpm",
        transmission:"Hewland FG400 5-speed manual",
        tyres:["Firestone"],
        chasis:"Single Seater Alumunium Monocoque",
        weight:"550kg",
        drivers: ["Emerson Fittipaldi"],
        constructorPoints: 61,
        image: "/assets/1970-1979/1972Lotus72D.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Tyrrell Ford 006",
        year: 1973,
        team: "Tyrrell Ford",
        engineName:"Ford Cosworth DFV",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2993cc",
        enginePower:"450BHP @10000rpm",
        transmission:"Hewland FG400 5-speed manual",
        tyres:["Goodyear"],
        chasis:"Single Seater Alumunium Monocoque",
        weight:"578kg",
        drivers: ["Jackie Stewart", "Francois Cevert", "Chris Amon"],
        constructorPoints: 73,
        image: "/assets/1970-1979/1973Tyrrell006.jpg",
        isWDC: true,
        isWCC: false,
    },
    {
        name: "Lotus Ford 72E",
        year: 1973,
        team: "Lotus Ford",
        engineName:"Ford Cosworth DFV",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2993cc",
        enginePower:"450BHP @10800rpm",
        transmission:"Hewland FG400 5-speed manual",
        tyres:["Firestone"],
        chasis:"Single Seater Alumunium Monocoque",
        weight:"570kg",
        drivers: ["Emerson Fittipaldi", "Ronnie Peterson"],
        constructorPoints: 92,
        image: "/assets/1970-1979/1973Lotus72E.jpg",
        isWDC: false,
        isWCC: true,
    },
    {
        name: "McLaren Ford M23",
        year: 1974,
        team: "McLaren Ford",
        engineName:"Ford Cosworth DFV",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2993cc",
        enginePower:"465BHP @10800rpm",
        transmission:"Hewland FG400 5/6-speed manual",
        tyres:["Goodyear"],
        chasis:"Single Seater Alumunium Monocoque",
        weight:"575kg",
        drivers: ["Emerson Fittipaldi", "Denny Hulme", "Mike Hailwood"],
        constructorPoints: 73,
        image: "/assets/1970-1979/1974McLarenM23.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Ferrari 312T",
        year: 1975,
        team: "Ferrari",
        engineName:"Ferrari Tipo 015",
        engineConfig:"Flat-12 Mid Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2991cc",
        enginePower:"495BHP @12200rpm",
        transmission:"Ferrari Tipo 015 5-speed manual transverse gearbox",
        tyres:["Goodyear"],
        chasis:"Single Seater Steel tube frame",
        weight:"570kg",
        drivers: ["Niki Lauda", "Clay Regazzoni"],
        constructorPoints: 72.5,
        image: "/assets/1970-1979/1975Ferrari312T.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "McLaren Ford M23",
        year: 1976,
        team: "McLaren Ford",
        engineName:"Ford Cosworth DFV",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2993cc",
        enginePower:"465BHP @10800rpm",
        transmission:"Hewland FG400 5/6-speed manual",
        tyres:["Goodyear"],
        chasis:"Single Seater Alumunium Monocoque",
        weight:"575kg",
        drivers: ["James Hunt", "Jochen Mass"],
        constructorPoints: 74,
        image: "/assets/1970-1979/1976McLarenM23.jpg",
        isWDC: true,
        isWCC: false,
    },
    {
        name: "Ferrari 312T2",
        year: 1976,
        team: "Ferrari",
        engineName:"Ferrari Tipo 015",
        engineConfig:"Flat-12 Mid Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2991cc",
        enginePower:"500BHP @12200rpm",
        transmission:"Ferrari Tipo 015 5-speed manual transverse gearbox",
        tyres:["Goodyear"],
        chasis:"Single Seater Steel tube frame",
        weight:"560kg",
        drivers: ["Niki Lauda", "Clay Regazzoni", "Carlos Reutemann"],
        constructorPoints: 83,
        image: "/assets/1970-1979/1976Ferrari312T2.jpg",
        isWDC: false,
        isWCC: true,
    },
    {
        name: "Ferrari 312T2B",
        year: 1977,
        team: "Ferrari",
        engineName:"Ferrari Tipo 015",
        engineConfig:"Flat-12 Mid Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2991cc",
        enginePower:"500BHP @12200rpm",
        transmission:"Ferrari Tipo 015 5-speed manual transverse gearbox",
        tyres:["Goodyear"],
        chasis:"Single Seater Steel tube frame",
        weight:"560kg",
        drivers: ["Niki Lauda", "Carlos Reutemann"],
        constructorPoints: 95,
        image: "/assets/1970-1979/1977Ferrari312T2B.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Lotus Ford 79",
        year: 1978,
        team: "Lotus Ford",
        engineName:"Ford Cosworth DFV",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2993cc",
        enginePower:"475BHP @11000rpm",
        transmission:"Hewland FG400 5/6-speed manual",
        tyres:["Goodyear"],
        chasis:"Single Seater Alumunium Monocoque",
        weight:"573kg",
        drivers: ["Mario Andretti", "Ronnie Peterson", "Hector Rebaque"],
        constructorPoints: 86,
        image: "/assets/1970-1979/1978Lotus79.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Ferrari 312T4",
        year: 1979,
        team: "Ferrari",
        engineName:"Ferrari Tipo 015",
        engineConfig:"Flat-12 Mid Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2991cc",
        enginePower:"515BHP @12300rpm",
        transmission:"Ferrari Tipo 015 5-speed manual transverse gearbox",
        tyres:["Goodyear"],
        chasis:"Single Seater Steel tube frame",
        weight:"590kg",
        drivers: ["Jody Scheckter", "Gilles Villeneuve"],
        constructorPoints: 113,
        image: "/assets/1970-1979/1979Ferrari312T4.jpg",
        isWDC: true,
        isWCC: true,
    },

    {
        name: "Williams Ford FW07B",
        year: 1980,
        team: "Williams Ford",
        engineName:"Ford Cosworth DVF",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2993cc",
        enginePower:"515BHP @12300rpm",
        transmission:"Hewland FGA 400 5-speed manual",
        tyres:["Goodyear"],
        chasis:"Single Seater Alumunium Monocoque",
        weight:"585kg",
        drivers: ["Alan Jones", "Carlos Reutemann"],
        constructorPoints: 120,
        image: "/assets/1980-1989/1980WilliamsFW07B.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Brabham Ford BT49C",
        year: 1981,
        team: "Brabham Ford",
        engineName:"Ford Cosworth DVF",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2993cc",
        enginePower:"515BHP @12300rpm",
        transmission:"Hewland FGA 400 6-speed manual",
        tyres:["Goodyear"],
        chasis:"Single Seater Alumunium Alloy Monocoque",
        weight:"580kg",
        drivers: ["Nelson Piquet", "Hector Rebaque"],
        constructorPoints: 61,
        image: "/assets/1980-1989/1981BrabhamBT49C.jpg",
        isWDC: true,
        isWCC: false,
    },
    {
        name: "Williams Ford FW07C",
        year: 1981,
        team: "Williams Ford",
        engineName:"Ford Cosworth DVF",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2993cc",
        enginePower:"515BHP @12300rpm",
        transmission:"Hewland FGA 400 5-speed manual",
        tyres:["Goodyear"],
        chasis:"Single Seater Alumunium Monocoque",
        weight:"540kg",
        drivers: ["Carlos Reutemann", "Alan Jones"],
        constructorPoints: 95,
        image: "/assets/1980-1989/1981WilliamsFW07C.jpg",
        isWDC: false,
        isWCC: true,
    },
    {
        name: "Williams Ford FW08",
        year: 1982,
        team: "Williams Ford",
        engineName:"Ford Cosworth DVF",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally aspirated",
        engineDisplacement:"2993cc",
        enginePower:"515BHP @12300rpm",
        transmission:"Hewland FGA 400 5-speed manual",
        tyres:["Goodyear"],
        chasis:"Single Seater Alumunium Honeycomb Monocoque",
        weight:"500kg",
        drivers: ["Keke Rosberg", "Derek Daly", "Carlos Reutemann"],
        constructorPoints: 58,
        image: "/assets/1980-1989/1982WilliamsFW08.jpg",
        isWDC: true,
        isWCC: false,
    },
    {
        name: "Ferrari 126 C2",
        year: 1982,
        team: "Ferrari",
        engineName:"Ferrari 031",
        engineConfig:"V6 120 degree Mid Mounted",
        compressor:"Turbocharged",
        engineDisplacement:"1496cc",
        enginePower:"600BHP @11500rpm",
        transmission:"Ferrari 6-speed manual",
        tyres:["Goodyear"],
        chasis:"Single Seater Carbon Fibre and Alumunium Honeycomb Composite Monocoque",
        weight:"595kg",
        drivers: ["Didier Pironi", "Patrick Tambay", "Gilles Villeneuve", "Mario Andretti"],
        constructorPoints: 74,
        image: "/assets/1980-1989/1982Ferrari126C2.jpg",
        isWDC: false,
        isWCC: true,
    },
    {
        name: "Brabham BMW BT52",
        year: 1983,
        team: "Brabham BMW",
        engineName:"BMW M12",
        engineConfig:"Straight 4 Mid Mounted",
        compressor:"Turbocharged",
        engineDisplacement:"1499cc",
        enginePower:"850BHP @11000rpm",
        transmission:"Brabham/Hewland 5/6-speed manual Weismann Differential",
        tyres:["Michelin"],
        chasis:"Single Seater Carbon Fibre Monocoque with rear subframe",
        weight:"540kg",
        drivers: ["Nelson Piquet", "Riccardo Patrese"],
        constructorPoints: 72,
        image: "/assets/1980-1989/1983BrabhamBT52.jpg",
        isWDC: true,
        isWCC: false,
    },
    {
        name: "Ferrari 126 C3",
        year: 1983,
        team: "Ferrari",
        engineName:"Ferrari 031",
        engineConfig:"V6 120 degree Mid Mounted",
        compressor:"Turbocharged",
        engineDisplacement:"1496cc",
        enginePower:"600BHP @10500rpm",
        transmission:"Ferrari 6-speed manual",
        tyres:["Goodyear"],
        chasis:"Single Seater Carbon Fibre and Alumunium Honeycomb Composite Monocoque",
        weight:"552kg",
        drivers: ["Rene Arnoux", "Patrick Tambay"],
        constructorPoints: 89,
        image: "/assets/1980-1989/1983Ferrari126C3.jpg",
        isWDC: false,
        isWCC: true,
    },
    {
        name: "McLaren TAG MP4/2",
        year: 1984,
        team: "McLaren TAG",
        engineName:"TAG Porsche TTE P01",
        engineConfig:"V6 90 degree Mid Mounted",
        compressor:"Turbocharged",
        engineDisplacement:"1499cc",
        enginePower:"900HP",
        transmission:"McLaren / Hewland FGB 5-speed manual",
        tyres:["Michelin"],
        chasis:"Single Seater Carbon Fibre Honeycomb Monocoque",
        weight:"540kg",
        drivers: ["Niki Lauda", "Alain Prost"],
        constructorPoints: 143.5,
        image: "/assets/1980-1989/1984McLarenMP4-2.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "McLaren TAG MP4/2B",
        year: 1985,
        team: "McLaren TAG",
        engineName:"TAG Porsche TTE P01",
        engineConfig:"V6 90 degree Mid Mounted",
        compressor:"Turbocharged",
        engineDisplacement:"1499cc",
        enginePower:"960HP",
        transmission:"McLaren / Hewland FGB 5-speed manual",
        tyres:["Goodyear"],
        chasis:"Single Seater Carbon Fibre Honeycomb Monocoque",
        weight:"540kg",
        drivers: ["Alain Prost", "Niki Lauda"],
        constructorPoints: 90,
        image: "/assets/1980-1989/1985McLarenMP4-2B.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "McLaren TAG MP4/2C",
        year: 1986,
        team: "McLaren TAG",
        engineName:"TAG Porsche TTE P01",
        engineConfig:"V6 90 degree Mid Mounted",
        compressor:"Turbocharged",
        engineDisplacement:"1499cc",
        enginePower:"960HP",
        transmission:"McLaren / Hewland FGB 5-speed manual",
        tyres:["Goodyear"],
        chasis:"Single Seater Carbon Fibre Honeycomb Monocoque",
        weight:"540kg",
        drivers: ["Alain Prost", "Keke Rosberg"],
        constructorPoints: 96,
        image: "/assets/1980-1989/1986McLarenMP4-2C.jpg",
        isWDC: true,
        isWCC: false,
    },
    {
        name: "Williams Honda FW11",
        year: 1986,
        team: "Williams Honda",
        engineName:"Honda RA166E",
        engineConfig:"V6 90 degree Mid Mounted",
        compressor:"Turbocharged",
        engineDisplacement:"1494cc",
        enginePower:"1200HP @12000rpm",
        transmission:"Williams / Hewland 6-speed manual",
        tyres:["Goodyear"],
        chasis:"Single Seater Moulded Carbon Composite Monocoque",
        weight:"540kg",
        drivers: ["Nigel Mansell", "Nelson Piquet"],
        constructorPoints: 141,
        image: "/assets/1980-1989/1986WilliamsFW11.jpg",
        isWDC: false,
        isWCC: true,
    },
    {
        name: "Williams Honda FW11B",
        year: 1987,
        team: "Williams Honda",
        engineName:"Honda RA167E",
        engineConfig:"V6 90 degree Mid Mounted",
        compressor:"Turbocharged",
        engineDisplacement:"1494cc",
        enginePower:"1200HP @12000rpm",
        transmission:"Williams / Hewland 6-speed manual",
        tyres:["Goodyear"],
        chasis:"Single Seater Moulded Carbon Composite Monocoque",
        weight:"540kg",
        drivers: ["Nelson Piquet", "Nigel Mansell", "Riccardo Patrese"],
        constructorPoints: 137,
        image: "/assets/1980-1989/1987WilliamsFW11B.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "McLaren Honda MP4/4",
        year: 1988,
        team: "Mclaren Honda",
        engineName:"Honda RA168E",
        engineConfig:"V6 80 degree Mid Mounted",
        compressor:"Turbocharged",
        engineDisplacement:"1494cc",
        enginePower:"675HP @12500rpm",
        transmission:"Weismann-McLaren 6-Speed manual",
        tyres:["Goodyear"],
        chasis:"Single Seater Carbon Fibre Honeycomb Monocoque",
        weight:"540kg",
        drivers: ["Ayrton Senna", "Alain Prost"],
        constructorPoints: 199,
        image: "/assets/1980-1989/1988McLarenMP4-4.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "McLaren Honda MP4/5",
        year: 1989,
        team: "Mclaren Honda",
        engineName:"Honda RA109E",
        engineConfig:"V10 72 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"3496cc",
        enginePower:"675HP @13500rpm",
        transmission:"Weismann-McLaren 6-Speed manual",
        tyres:["Goodyear"],
        chasis:"Single Seater Carbon Fibre and Kevlar Monocoque",
        weight:"470kg",
        drivers: ["Alain Prost","Ayrton Senna"],
        constructorPoints: 141,
        image: "/assets/1980-1989/1989McLarenMP4-5.jpg",
        isWDC: true,
        isWCC: true,
    },

    {
        name: "McLaren Honda MP4/5B",
        year: 1990,
        team: "Mclaren Honda",
        engineName:"Honda RA100E",
        engineConfig:"V10 72 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"3496cc",
        enginePower:"710HP @13500rpm",
        transmission:"Weismann-McLaren 6-Speed manual",
        tyres:["Goodyear"],
        chasis:"Single Seater Carbon Fibre and Kevlar Monocoque",
        weight:"500kg",
        drivers: ["Ayrton Senna", "Gerhard Berger"],
        constructorPoints: 121,
        image: "/assets/1990-1999/1990McLarenMP4-5B.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "McLaren Honda MP4/6",
        year: 1991,
        team: "Mclaren Honda",
        engineName:"Honda RA121E",
        engineConfig:"V12 60 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"3497cc",
        enginePower:"780HP @13500rpm",
        transmission:"Weismann-McLaren 6-Speed manual",
        tyres:["Goodyear"],
        chasis:"Single Seater Carbon Fibre and Kevlar Monocoque",
        weight:"575kg",
        drivers: ["Ayrton Senna", "Gerhard Berger"],
        constructorPoints: 139,
        image: "/assets/1990-1999/1991McLarenMP4-6.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Williams Renault FW14B",
        year: 1992,
        team: "Williams Renault",
        engineName:"Renault RS4",
        engineConfig:"V10 67 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"3493cc",
        enginePower:"750HP @13000rpm",
        transmission:"Williams 6 Speed Sequential Semi-Automatic",
        tyres:["Goodyear"],
        chasis:"Single Seater Carbon Fibre and Honeycomb Composite Structure",
        weight:"510kg",
        drivers: ["Nigel Mansell", "Ricardo Patrese"],
        constructorPoints: 164,
        image: "/assets/1990-1999/1992WilliamsFW14B.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Williams Renault FW15C",
        year: 1993,
        team: "Williams Renault",
        engineName:"Renault RS5",
        engineConfig:"V10 67 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"3493cc",
        enginePower:"780HP @13800rpm",
        transmission:"Williams 6 Speed Sequential Semi-Automatic",
        tyres:["Goodyear"],
        chasis:"Single Seater Carbon Fibre and Aramid Monocoque",
        weight:"505kg",
        drivers: ["Alain Prost", "Damon Hill"],
        constructorPoints: 168,
        image: "/assets/1990-1999/1993WilliamsFW15C.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Benetton Ford B194",
        year: 1994,
        team: "Benetton Ford",
        engineName:"Ford EC Zetec-R",
        engineConfig:"V8 75 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"3498cc",
        enginePower:"740HP @14500rpm",
        transmission:"Benetton Transverse 6-Speed Sequential Semi-Automatic",
        tyres:["Goodyear"],
        chasis:"Single Seater Carbon Fibre Monocoque",
        weight:"515kg",
        drivers: ["Michael Schumacher", "Jos Verstappen"],
        constructorPoints: 103,
        image: "/assets/1990-1999/1994BenettonB194.jpg",
        isWDC: true,
        isWCC: false,
    },
    {
        name: "Williams Renault FW16C",
        year: 1994,
        team: "Williams Renault",
        engineName:"Renault RS6C",
        engineConfig:"V10 67 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"3493cc",
        enginePower:"830HP @14300rpm",
        transmission:"Williams 6 Speed Sequential Semi-Automatic",
        tyres:["Goodyear"],
        chasis:"Single Seater Carbon Fibre and Aramid Monocoque",
        weight:"505kg",
        drivers: ["Damon Hill", "David Coulthard", "Nigel Mansell", "Ayrton Senna"],
        constructorPoints: 118,
        image: "/assets/1990-1999/1994WilliamsFW16.jpg",
        isWDC: false,
        isWCC: true,
    },
    {
        name: "Benetton Renault B195",
        year: 1995,
        team: "Benetton Renault",
        engineName:"Renault RS7",
        engineConfig:"V10 67 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"3000cc",
        enginePower:"700HP @15600rpm",
        transmission:"Benetton Transverse 6-Speed Sequential Semi-Automatic",
        tyres:["Goodyear"],
        chasis:"Single Seater Carbon Fibre Monocoque",
        weight:"515kg",
        drivers: ["Michael Schumacher", "Johny Herbert"],
        constructorPoints: 137,
        image: "/assets/1990-1999/1995BenettonB195.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Williams Renault FW18",
        year: 1996,
        team: "Williams Renault",
        engineName:"Renault RS8B",
        engineConfig:"V10 67 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"2998cc",
        enginePower:"700HP @16000rpm",
        transmission:"Williams 6 Speed Sequential Semi-Automatic",
        tyres:["Goodyear"],
        chasis:"Single Seater Carbon/Epoxy Composite Monocoque",
        weight:"595kg",
        drivers: ["Damon Hill", "Jacques Villeneuve"],
        constructorPoints: 175,
        image: "/assets/1990-1999/1996WilliamsFW18.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Williams Renault FW19",
        year: 1997,
        team: "Williams Renault",
        engineName:"Mechachrome-built Renault RS9B",
        engineConfig:"V10 71 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"2998cc",
        enginePower:"760HP @17000rpm",
        transmission:"Williams/Komatsu 6-Speed Transverse Sequential Semi-Automatic",
        tyres:["Goodyear"],
        chasis:"Single Seater Carbon/Epoxy Composite Monocoque",
        weight:"600kg",
        drivers: ["Jacques Villeneuve", "Hainz-Harald Frentzen"],
        constructorPoints: 123,
        image: "/assets/1990-1999/1997WilliamsFW19.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "McLaren Mercedes MP4/13",
        year: 1998,
        team: "McLaren Mercedes",
        engineName:"Mercedes-Benz FO-110G",
        engineConfig:"V10 72 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"2998cc",
        enginePower:"800HP @17000rpm",
        transmission:"McLaren Six-Speed Longitudinal Semi-Automatic Sequential.",
        tyres:["Bridgestone"],
        chasis:"Single Seater Moulded Carbon-Fibre Composite Structure",
        weight:"600kg",
        drivers: ["Mika Hakkinen", "David Coulthard"],
        constructorPoints: 156,
        image: "/assets/1990-1999/1998McLarenMP4-13.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "McLaren Mercedes MP4/14",
        year: 1999,
        team: "McLaren Mercedes",
        engineName:"Mercedes-Benz FO-110H",
        engineConfig:"V10 72 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"2998cc",
        enginePower:"810HP @17000rpm",
        transmission:"McLaren 7-speed sequential",
        tyres:["Bridgestone"],
        chasis:"Single Seater Moulded Carbon Fibre/Aluminium Honeycomb Composite Structure.",
        weight:"600kg",
        drivers: ["Mika Hakkinen", "David Coulthard"],
        constructorPoints: 124,
        image: "/assets/1990-1999/1999McLarenMP4-14.jpg",
        isWDC: true,
        isWCC: false,
    },
    {
        name: "Ferrari F399",
        year: 1999,
        team: "Ferrari",
        engineName:"Ferrari Tipo 048/B/C",
        engineConfig:"V10 80 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"2998cc",
        enginePower:"790HP @16300rpm",
        transmission:"Ferrari 7-speed Longitudinal Sequential Semi-Automatic",
        tyres:["Bridgestone"],
        chasis:"Single Seater Carbon Fibre Honeycomb Composite Structure.",
        weight:"600kg",
        drivers: ["Eddie Irvine", "Michael Schumacher", "Mika Salo"],
        constructorPoints: 128,
        image: "/assets/1990-1999/1999FerrariF399.jpg",
        isWDC: false,
        isWCC: true,
    },

    {
        name: "Ferrari F1-2000",
        year: 2000,
        team: "Ferrari",
        engineName:"Ferrari Tipo 049",
        engineConfig:"V10 90 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"2996cc",
        enginePower:"815HP @17300rpm",
        transmission:"Ferrari 7-speed Semi-Automatic Sequential",
        tyres:["Bridgestone"],
        chasis:"Single Seater Moulded Carbon Fibre & Honeycomb Composite Structure",
        weight:"600kg",
        drivers: ["Michael Schumacher", "Rubens Barichello"],
        constructorPoints: 170,
        image: "/assets/2000-2009/2000FerrariF1-2000.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Ferrari F2001",
        year: 2001,
        team: "Ferrari",
        engineName:"Ferrari Tipo 050",
        engineConfig:"V10 90 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"3000cc",
        enginePower:"825HP @17300rpm",
        transmission:"Ferrari 7-speed Semi-Automatic Sequential Limited-slip Differential Gearbox + Reverse",
        tyres:["Bridgestone"],
        chasis:"Single Seater Moulded Carbon Fibre & Honeycomb Composite Structure",
        weight:"600kg",
        drivers: ["Michael Schumacher", "Rubens Barichello"],
        constructorPoints: 179,
        image: "/assets/2000-2009/2001FerrariF2001.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Ferrari F2002",
        year: 2002,
        team: "Ferrari",
        engineName:"Ferrari Tipo 051/B/C",
        engineConfig:"V10 90 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"3000cc",
        enginePower:"835HP @17300rpm",
        transmission:"Ferrari 7-speed Semi-Automatic Sequential Limited-slip Differential Gearbox + Reverse",
        tyres:["Bridgestone"],
        chasis:"Single Seater Moulded Carbon Fibre & Honeycomb Composite Structure",
        weight:"600kg",
        drivers: ["Michael Schumacher", "Rubens Barichello"],
        constructorPoints: 221,
        image: "/assets/2000-2009/2002FerrariF2002.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Ferrari F2003-GA",
        year: 2003,
        team: "Ferrari",
        engineName:"Ferrari Tipo 052",
        engineConfig:"V10 90 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"3000cc",
        enginePower:"930HP @19000rpm",
        transmission:"Ferrari 7-speed Semi-Automatic Sequential Limited-slip Differential Gearbox + Reverse",
        tyres:["Bridgestone"],
        chasis:"Single Seater Moulded Carbon Fibre & Honeycomb Composite Structure",
        weight:"600kg",
        drivers: ["Michael Schumacher", "Rubens Barichello"],
        constructorPoints: 158,
        image: "/assets/2000-2009/2003FerrariF2003.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Ferrari F2004",
        year: 2004,
        team: "Ferrari",
        engineName:"Ferrari Tipo 053",
        engineConfig:"V10 90 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"3000cc",
        enginePower:"940HP @19000rpm",
        transmission:"Ferrari 7-speed Semi-Automatic Sequential Limited-slip Differential Gearbox + Reverse",
        tyres:["Bridgestone"],
        chasis:"Single Seater Moulded Carbon Fibre & Honeycomb Composite Structure",
        weight:"605kg",
        drivers: ["Michael Schumacher", "Rubens Barichello"],
        constructorPoints: 262,
        image: "/assets/2000-2009/2004FerrariF2004.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Renault R25",
        year: 2005,
        team: "Renault",
        engineName:"Mechachrome-built Renault RS25",
        engineConfig:"V10 72 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"3000cc",
        enginePower:"900HP @19000rpm",
        transmission:"Renault 6-speed Sequential Semi-Automatic Gearbox",
        tyres:["Michellin"],
        chasis:"Single Seater Carbon Fibre Monocoque",
        weight:"605kg",
        drivers: ["Fernando Alonso", "Giancarlo Fisichella"],
        constructorPoints: 191,
        image: "/assets/2000-2009/2005RenaultR25.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Renault R26",
        year: 2006,
        team: "Renault",
        engineName:"Mechachrome-built Renault RS26",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"2398cc",
        enginePower:"775HP @20500rpm",
        transmission:"Renault 7-speed + 1 Reverse Titanium Longitudinal Sequential Semi-Automatic Transmission",
        tyres:["Michellin"],
        chasis:"Single Seater Carbon Fibre Monocoque",
        weight:"605kg",
        drivers: ["Fernando Alonso", "Giancarlo Fisichella"],
        constructorPoints: 206,
        image: "/assets/2000-2009/2006RenaultR26.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Ferrari F2007",
        year: 2007,
        team: "Ferrari",
        engineName:"Ferrari Tipo 056-2007",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"2398cc",
        enginePower:"800HP @19000rpm",
        transmission:"Ferrari 7-speed transverse gearbox Quick Shift",
        tyres:["Bridgestone"],
        chasis:"Single Seater Carbon-fibre and Honeycomb Composite Monocoque",
        weight:"600kg",
        drivers: ["Kimi Raikkonen", "Felipe Massa"],
        constructorPoints: 204,
        image: "/assets/2000-2009/2007FerrariF2007.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "McLaren Mercedes MP4/-23",
        year: 2008,
        team: "McLaren Mercedes",
        engineName:"Mercedes-Benz FO 108V",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"2398cc",
        enginePower:"810HP @19000rpm",
        transmission:"McLaren 7-speed + 1 Reverse Sequential Seamless Semi-Automatic",
        tyres:["Bridgestone"],
        chasis:"Single Seater Moulded Carbon Fibre/aluminium honeycomb composite",
        weight:"605kg",
        drivers: ["Lewis Hamilton", "Heiki Kovalainen"],
        constructorPoints: 151,
        image: "/assets/2000-2009/2008McLarenMP4-23.jpg",
        isWDC: true,
        isWCC: false,
    },
    {
        name: "Ferrari F2008",
        year: 2008,
        team: "Ferrari",
        engineName:"Ferrari Tipo 056-2008",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"2398cc",
        enginePower:"785HP @19000rpm",
        transmission:"Ferrari 7-speed transverse gearbox Quick Shift",
        tyres:["Bridgestone"],
        chasis:"Single Seater Carbon-fibre and Honeycomb Composite Monocoque",
        weight:"600kg",
        drivers: ["Felipe Massa", "Kimi Raikkonen"],
        constructorPoints: 172,
        image: "/assets/2000-2009/2008FerrariF2008.jpg",
        isWDC: false,
        isWCC: true,
    },
    {
        name: "Brawn Mercedes BGP 001",
        year: 2009,
        team: "Brawn Mercedes",
        engineName:"Mercedes-Benz FO 108W",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"2398cc",
        enginePower:"750HP @18000rpm",
        transmission:"Brawn GP 7-speed + 1 Reverse Semi-Automatic.",
        tyres:["Bridgestone"],
        chasis:"Single Seater Moulded Carbon Fibre and Honeycomb Composite Monocoque.",
        weight:"605kg",
        drivers: ["Jenson Button", "Rubens Barichello"],
        constructorPoints: 172,
        image: "/assets/2000-2009/2009BrawnGP001.jpg",
        isWDC: true,
        isWCC: true,
    },

    {
        name: "RedBull Racing Renault RB06",
        year: 2010,
        team: "RedBull Racing Renault",
        engineName:"Renault RS27-2010",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"2398cc",
        enginePower:"750HP @18000rpm",
        transmission:"RedBull 7-speed + 1 Reverse Semi-Automatic Hydraulic",
        tyres:["Bridgestone"],
        chasis:"Single Seater Carbon Fibre and Honeycomb Composite Monocoque.",
        weight:"620kg",
        drivers: ["Sebastian Vettel", "Mark Webber"],
        constructorPoints: 498,
        image: "/assets/2010-2019/2010RedBullRacingRB06.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "RedBull Racing Renault RB07",
        year: 2011,
        team: "RedBull Racing Renault",
        engineName:"Renault RS27-2012",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"2400cc",
        enginePower:"750HP @18000rpm",
        transmission:"RedBull 7-speed + 1 Reverse Semi-Automatic Hydraulic",
        tyres:["Pirelli"],
        chasis:"Single Seater Carbon Fibre and Honeycomb Composite Monocoque.",
        weight:"640kg",
        drivers: ["Sebastian Vettel", "Mark Webber"],
        constructorPoints: 650,
        image: "/assets/2010-2019/2011RedBullRacingRB07.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "RedBull Racing Renault RB08",
        year: 2012,
        team: "RedBull Racing Renault",
        engineName:"Renault RS27-2012 with KERS",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"2400cc",
        enginePower:"750HP @18000rpm",
        transmission:"Red Bull 7-speed Hydraulic Power Shift",
        tyres:["Pirelli"],
        chasis:"Single Seater Carbon Fibre Composite Monocoque.",
        weight:"640kg",
        drivers: ["Sebastian Vettel", "Mark Webber"],
        constructorPoints: 460,
        image: "/assets/2010-2019/2012RedBullRacingRB08.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "RedBull Racing Renault RB09",
        year: 2013,
        team: "RedBull Racing Renault",
        engineName:"Renault RS27-2013 with KERS",
        engineConfig:"V8 90 degree Mid Mounted",
        compressor:"Naturally Aspirated",
        engineDisplacement:"2400cc",
        enginePower:"750HP @18000rpm",
        transmission:"Red Bull 7-speed Hydraulic Power Shift",
        tyres:["Pirelli"],
        chasis:"Single Seater Carbon Fibre Composite Monocoque.",
        weight:"642kg",
        drivers: ["Sebastian Vettel", "Mark Webber"],
        constructorPoints: 596,
        image: "/assets/2010-2019/2013RedBullRacingRB09.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Mercedes F1 W05 Hybrid",
        year: 2014,
        team: "Mercedes F1",
        engineName:"Mercedes-Benz PU106A Hybrid",
        engineConfig:"V6 90 degree Mid Mounted",
        compressor:"Turbocharged Hybrid",
        engineDisplacement:"1600cc",
        enginePower:"840HP @15000rpm",
        transmission:"Mercedes-Xtrac 8-speed Semi Automatic Seamless + 1 Reverse",
        tyres:["Pirelli"],
        chasis:"Single Seater Moulded Carbon Fibre and Honeycomb Composite Monocoque.",
        weight:"691kg",
        drivers: ["Lewis Hamilton", "Nico Rosberg"],
        constructorPoints: 701,
        image: "/assets/2010-2019/2014MercedesW05.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Mercedes F1 W06 Hybrid",
        year: 2015,
        team: "Mercedes F1",
        engineName:"Mercedes-Benz PU106B Hybrid",
        engineConfig:"V6 90 degree Mid Mounted",
        compressor:"Turbocharged Hybrid",
        engineDisplacement:"1600cc",
        enginePower:"870HP @15000rpm",
        transmission:"Mercedes-Xtrac 8-speed Semi Automatic Seamless + 1 Reverse",
        tyres:["Pirelli"],
        chasis:"Single Seater Moulded Carbon Fibre and Honeycomb Composite Monocoque.",
        weight:"702kg",
        drivers: ["Lewis Hamilton", "Nico Rosberg"],
        constructorPoints: 703,
        image: "/assets/2010-2019/2015MercedesW06.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Mercedes F1 W07 Hybrid",
        year: 2016,
        team: "Mercedes F1",
        engineName:"Mercedes-Benz PU106C Hybrid",
        engineConfig:"V6 90 degree Mid Mounted",
        compressor:"Turbocharged Hybrid",
        engineDisplacement:"1600cc",
        enginePower:"900HP @15000rpm",
        transmission:"Mercedes-Xtrac 8-speed Semi Automatic Seamless + 1 Reverse",
        tyres:["Pirelli"],
        chasis:"Single Seater Moulded Carbon Fibre and Honeycomb Composite Monocoque.",
        weight:"702kg",
        drivers: ["Nico Rosberg", "Lewis Hamilton"],
        constructorPoints: 765,
        image: "/assets/2010-2019/2016MercedesW07.jpg",
        isWDC: true,
        isWCC: true,
    }, 
    {
        name: "Mercedes F1 W08 EQ Power",
        year: 2017,
        team: "Mercedes F1",
        engineName:"Mercedes-Benz M08 EQ Power+",
        engineConfig:"V6 90 degree Mid Mounted",
        compressor:"Turbocharged Hybrid",
        engineDisplacement:"1600cc",
        enginePower:"940HP @15000rpm",
        transmission:"Mercedes-Xtrac 8-speed Semi Automatic Seamless + 1 Reverse",
        tyres:["Pirelli"],
        chasis:"Single Seater Moulded Carbon Fibre and Honeycomb Composite Monocoque.",
        weight:"728kg",
        drivers: ["Lewis Hamilton", "Valteri Bottas"],
        constructorPoints: 668,
        image: "/assets/2010-2019/2017MercedesW08.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Mercedes F1 W09 EQ Power",
        year: 2018,
        team: "Mercedes F1",
        engineName:"Mercedes-Benz M09 EQ Power+",
        engineConfig:"V6 90 degree Mid Mounted",
        compressor:"Turbocharged Hybrid",
        engineDisplacement:"1600cc",
        enginePower:"1000HP @15000rpm",
        transmission:"Mercedes-Xtrac 8-speed Semi Automatic Seamless + 1 Reverse",
        tyres:["Pirelli"],
        chasis:"Single Seater Moulded Carbon Fibre and Honeycomb Composite Monocoque.",
        weight:"733kg",
        drivers: ["Lewis Hamilton", "Valteri Bottas"],
        constructorPoints: 655,
        image: "/assets/2010-2019/2018MercedesW09.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "Mercedes F1 W10 EQ Power",
        year: 2019,
        team: "Mercedes F1",
        engineName:"Mercedes-Benz M10 EQ Power+",
        engineConfig:"V6 90 degree Mid Mounted",
        compressor:"Turbocharged Hybrid",
        engineDisplacement:"1600cc",
        enginePower:"1000HP @15000rpm",
        transmission:"Mercedes-Xtrac 8-speed Semi Automatic Seamless + 1 Reverse",
        tyres:["Pirelli"],
        chasis:"Single Seater Moulded Carbon Fibre and Honeycomb Composite Monocoque.",
        weight:"743kg",
        drivers: ["Lewis Hamilton", "Valteri Bottas"],
        constructorPoints: 739,
        image: "/assets/2010-2019/2019MercedesW10.jpg",
        isWDC: true,
        isWCC: true,
    },

    {
        name: "Mercedes F1 W11 EQ Performance",
        year: 2020,
        team: "Mercedes F1",
        engineName:"Mercedes-Benz M11 EQ Power+",
        engineConfig:"V6 90 degree Mid Mounted",
        compressor:"Turbocharged Hybrid",
        engineDisplacement:"1600cc",
        enginePower:"1025HP @15000rpm",
        transmission:"Mercedes-Xtrac 8-speed Semi Automatic Seamless + 1 Reverse",
        tyres:["Pirelli"],
        chasis:"Single Seater Moulded Carbon Fibre and Honeycomb Composite Monocoque.",
        weight:"746kg",
        drivers: ["Lewis Hamilton", "Valteri Bottas"],
        constructorPoints: 573,
        image: "/assets/2020-2023/2020MercedesW11.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "RedBull Racing Honda RB16B",
        year: 2021,
        team: "RedBull Racing Honda",
        engineName:"Honda RA621H",
        engineConfig:"V6 90 degree Mid Mounted",
        compressor:"Turbocharged Hybrid",
        engineDisplacement:"1600cc",
        enginePower:"1080HP @15000rpm",
        transmission:"RedBull 8-speed Semi Automatic Seamless + 1 Reverse",
        tyres:["Pirelli"],
        chasis:"Single Seater Moulded Carbon Fibre and Honeycomb Composite Monocoque.",
        weight:"752kg",
        drivers: ["Max Verstappen", "Sergio Perez"],
        constructorPoints: 585.5,
        image: "/assets/2020-2023/2021RedBullRacingRB16B.jpg",
        isWDC: true,
        isWCC: false,
    },
    {
        name: "Mercedes F1 W12 EQ Performance",
        year: 2021,
        team: "Mercedes F1",
        engineName:"Mercedes-Benz M12 E Performance",
        engineConfig:"V6 90 degree Mid Mounted",
        compressor:"Turbocharged Hybrid",
        engineDisplacement:"1600cc",
        enginePower:"1070HP @15000rpm",
        transmission:"Mercedes-Xtrac 8-speed Semi Automatic Seamless + 1 Reverse",
        tyres:["Pirelli"],
        chasis:"Single Seater Moulded Carbon Fibre and Honeycomb Composite Monocoque.",
        weight:"752kg",
        drivers: ["Lewis Hamilton", "Valteri Bottas"],
        constructorPoints: 613.5,
        image: "/assets/2020-2023/2021MercedesW12.jpg",
        isWDC: false,
        isWCC: true,
        description:"The Mercedes-AMG F1 W11 dominated the 2020 season with superior aerodynamics and power."
    },
    {
        name: "RedBull Racing RBPT RB18",
        year: 2022,
        team: "RedBull Racing RBPT",
        engineName:"RedBull RBPTH001",
        engineConfig:"V6 90 degree Mid Mounted",
        compressor:"Turbocharged Hybrid",
        engineDisplacement:"1600cc",
        enginePower:"1080HP @15000rpm",
        transmission:"RedBull 8-speed Semi Automatic Seamless + 1 Reverse",
        tyres:["Pirelli"],
        chasis:"Single Seater Moulded Carbon Fibre and Honeycomb Composite Monocoque.",
        weight:"798kg",
        drivers: ["Max Verstappen", "Sergio Perez"],
        constructorPoints: 759,
        image: "/assets/2020-2023/2022RedBullRacingRB18.jpg",
        isWDC: true,
        isWCC: true,
    },
    {
        name: "RedBull Racing Honda RBPT RB19",
        year: 2023,
        team: "RedBull Racing RBPT",
        engineName:"RedBull RBPTH001",
        engineConfig:"V6 90 degree Mid Mounted",
        compressor:"Turbocharged Hybrid",
        engineDisplacement:"1600cc",
        enginePower:"1080HP @15000rpm",
        transmission:"RedBull 8-speed Semi Automatic Seamless + 1 Reverse",
        tyres:["Pirelli"],
        chasis:"Single Seater Moulded Carbon Fibre and Honeycomb Composite Monocoque.",
        weight:"798kg",
        drivers: ["Max Verstappen", "Sergio Perez"],
        constructorPoints: 860,
        image: "/assets/2020-2023/2023RedBullRacingRB19.jpg",
        isWDC: true,
        isWCC: true,
    },
];
